Fixes strapi bug for now and added french translation
ComfortablyCoding/strapi-plugin-publisher pull request #16
Opened 2022-03-03 16:41 UTC by GautierDele

closes #15

2022-03-03 16:44 UTC, GautierDele commented
@ComfortablyCoding considering strapi's reaction time to major bugs this could be great merging this one as quick as possible :)

I know you are a member of Strapi but I think you know about it too (see https://github.com/strapi/strapi/issues/11892 ...)

2022-03-03 17:35 UTC, ComfortablyCoding requested changes
Thank you for the PR!

I have left a comment on where I believe we can improve the changes. Other than the requested change all looks good.

P.S. I am not a Strapi Employee :sweat_smile:

2022-03-03 17:35 UTC, ComfortablyCoding commented on server/config/cron-tasks.js
> +							$lte: (new Date()).getTime(),
This is equivalent to Date.now() which makes is the preferred method of retrieving the unix epoch.

```suggestion
							$lte: Date.now(),
```

2022-03-03 18:25 UTC, GautierDele commented
Oh ok there is someone called "daedalus" on their team that's why

2022-03-04 03:38 UTC, ComfortablyCoding approved these changes

2022-03-04 03:39 UTC, merged

2022-03-04 03:46 UTC, ComfortablyCoding commented
Looks good, tyvm. It will be included in the next release.

>Oh ok there is someone called "daedalus" on their team that's why

I believe you are still referring to me, their is no daedalus on the Strapi team.

2022-03-04 10:47 UTC, GautierDele commented
@ComfortablyCoding could we make a release only for this since it's kinda blocking the usage ?

2022-03-04 13:02 UTC, ComfortablyCoding commented
Yes, I plan to do one today.

2022-03-04 20:29 UTC, ComfortablyCoding commented
Shipped in v1.1.3